"""baseline

Full schema as of the first Alembic revision: users, garments,
calendar_events, recommendation_events.

Adopting a PRE-Alembic database instead of a fresh one? Run
`alembic stamp head` (the tables already exist) — and if that database
predates email confirmation, first run
`UPDATE users SET email_verified = true` manually: login hard-blocks
unverified users, so a plain default-false column would lock out every
existing account. The backfill at the end of upgrade() encodes the same
rule for databases created by this migration (a no-op there, since the
tables start empty).

Revision ID: fd5045a8a55c
Revises:
Create Date: 2026-07-16 12:19:48.209375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd5045a8a55c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('avatar_key', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('style_preferences', sa.String(length=2000), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('subscription_status', sa.String(length=40), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_stripe_customer_id'), ['stripe_customer_id'], unique=False)

    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_events_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_user_id'), ['user_id'], unique=False)

    op.create_table('garments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('subcategory', sa.String(length=60), nullable=True),
    sa.Column('colors', sa.JSON(), nullable=False),
    sa.Column('pattern', sa.String(length=60), nullable=True),
    sa.Column('material', sa.String(length=60), nullable=True),
    sa.Column('formality', sa.String(length=30), nullable=True),
    sa.Column('warmth_rating', sa.Integer(), nullable=True),
    sa.Column('seasons', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('garments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_garments_user_id'), ['user_id'], unique=False)

    op.create_table('recommendation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_events_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###

    # Grandfather any pre-existing accounts as verified (see module docstring).
    # No-op on the empty databases this migration normally runs against.
    op.execute("UPDATE users SET email_verified = true")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendation_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_recommendation_events_created_at'))

    op.drop_table('recommendation_events')
    with op.batch_alter_table('garments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_garments_user_id'))

    op.drop_table('garments')
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_date'))

    op.drop_table('calendar_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_stripe_customer_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
